CREATE TABLE IF NOT EXISTS users (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
email varchar(255) NOT NULL,
login varchar(255) NOT NULL,
name varchar(255),
birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa (
id INTEGER PRIMARY KEY,
name varchar(10)
);

CREATE TABLE IF NOT EXISTS genre (
id INTEGER PRIMARY KEY,
name varchar(50)
);

CREATE TABLE IF NOT EXISTS film (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(255) NOT NULL,
description varchar(200),
release_date DATE NOT NULL,
duration int NOT NULL,
mpa_id int REFERENCES mpa(id)
);

CREATE TABLE IF NOT EXISTS film_genre (
film_id BIGINT REFERENCES film(id) ON DELETE CASCADE,
genre_id INTEGER REFERENCES genre(id) ON DELETE CASCADE,
PRIMARY KEY(film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS film_like (
film_id BIGINT REFERENCES film(id) ON DELETE CASCADE,
user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
PRIMARY KEY(film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friendship (
user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
friend_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
status varchar(20),
PRIMARY KEY(user_id, friend_id)
);

